language: python
install:
  - pip install -r requirements.txt
before_install:
      - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
      - mkdir geckodriver
      - tar -xzf geckodriver*.tar.gz -C geckodriver
      - export PATH=$PATH:$PWD/geckodriver
script:
  - python manage.py test